[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

fs_permissions = [{ access = "read", path="./src/AlienCodex/AlienCodex.json"}]
# See more config options https://github.com/gakonst/foundry/tree/master/config